{% set name = "gcsfuse" %}
{% set version = "40.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/GoogleCloudPlatform/gcsfuse/archive/v{{ version }}.tar.gz
  sha256: b36c068c7299ab2b48a221a04bff268d3248c4d04a390a336839494c59c16b3e

build:
  number: 0
  skip: true  # [not linux]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - {{ compiler('go-nocgo') }}
    - go-licenses
  host:
    - libfuse3

test:
  commands:
    - gcsfuse --help

about:
  home: https://github.com/GoogleCloudPlatform/gcsfuse
  license: Apache-2.0
  license_file:
    - LICENSE
    - license-files/
  summary: User-space file system for interacting with Google Cloud
  dev_url: https://github.com/GoogleCloudPlatform/gcsfuse

extra:
  recipe-maintainers:
    - danielnachun
